name: convohio
version: 0.0.1
author: Richard Griffith <scribe.griff@gmail.com>
description: A Server Side App for ConvoLab
homepage: http://www.scribegriff.com
dependencies:
  convolab:
    git: git://github.com/scribeGriff/ConvoLab.git
  unittest: any
  meta: any
